# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='text',
        ),
        migrations.RemoveField(
            model_name='player',
            name='title',
        ),
        migrations.AddField(
            model_name='player',
            name='is_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='join_players',
            field=models.ManyToManyField(to='game.Player'),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player_number',
            field=models.IntegerField(default=0),
        ),
    ]
