# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160606_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Color',
            field=models.CharField(max_length=10),
        ),
    ]
