# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160606_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Hand_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='Deck_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
