# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160606_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Last_card',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Num_of_joker',
        ),
    ]
