# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20160606_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Turn',
            field=models.IntegerField(default=0),
        ),
    ]
