# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20160606_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Is_finded',
            field=models.BooleanField(default=False),
        ),
    ]
