# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Get_pos',
        ),
    ]
